title: Your Portfolio
description: A showcase of my projects and skills
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social profiles
github_username: yourusername
linkedin_username: yourlinkedinname
twitter_username: yourtwitterhandle
email: your.email@example.com

# Portfolio settings
author: Your Name
job_title: Web Developer & Designer
location: City, Country

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag